export enum StoreType {
	BOOKS = "BOOKS",
	COSMETICS = "COSMETICS",
	ACADEMY = "ACADEMY",
	HANDCRAFTS = "HANDCRAFTS",
	SOUVENIRS = "SOUVENIRS",
	CLOTHING = "CLOTHING",
	SPORTS = "SPORTS",
	BAR = "BAR",
	RESTAURANT = "RESTAURANT",
	OTHER = "OTHER",
}
